
-- 1. Tabela anexos_anotacao
CREATE TABLE public.anexos_anotacao (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_anotacao BIGINT NOT NULL REFERENCES public.anotacoes_lead(id) ON DELETE CASCADE,
  id_empresa BIGINT NOT NULL REFERENCES public.empresas_geral(id),
  nome_arquivo TEXT NOT NULL,
  tipo_arquivo TEXT NOT NULL,
  tamanho BIGINT NOT NULL DEFAULT 0,
  storage_path TEXT NOT NULL,
  url_publica TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. RLS
ALTER TABLE public.anexos_anotacao ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users select own company anexos" ON public.anexos_anotacao
  FOR SELECT TO authenticated
  USING (id_empresa IN (SELECT empresa_id FROM user_empresa WHERE user_id = auth.uid()));

CREATE POLICY "Users insert own company anexos" ON public.anexos_anotacao
  FOR INSERT TO authenticated
  WITH CHECK (id_empresa IN (SELECT empresa_id FROM user_empresa WHERE user_id = auth.uid()));

CREATE POLICY "Users delete own company anexos" ON public.anexos_anotacao
  FOR DELETE TO authenticated
  USING (id_empresa IN (SELECT empresa_id FROM user_empresa WHERE user_id = auth.uid()));

CREATE POLICY "Admins all anexos" ON public.anexos_anotacao
  FOR ALL TO authenticated
  USING (is_admin(auth.uid()));

-- 3. Bucket storage
INSERT INTO storage.buckets (id, name, public) VALUES ('anexos-lead', 'anexos-lead', true);

-- 4. Storage RLS policies
CREATE POLICY "Authenticated users can upload anexos" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'anexos-lead');

CREATE POLICY "Anyone can view anexos" ON storage.objects
  FOR SELECT TO public
  USING (bucket_id = 'anexos-lead');

CREATE POLICY "Authenticated users can delete anexos" ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'anexos-lead');

-- 5. Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE anexos_anotacao;
